# KULLANICININ DÜZENLEYECEĞİ DOSYA

# Test etmek isterseniz aşağıdaki örnek echo komutunu kullanabilirsiniz:
# target_command: 'echo "[{\"host\": \"server1\", \"status\": \"active\", \"cpu_usage\": 90.5}, {\"host\": \"server2\", \"status\": \"active\", \"cpu_usage\": \"N/A\"}]"'

target_command: "/opt/bin/command -c"
output_format: "none" # Seçenekler: json, csv, excel, none

enable_filters: false # Filtreleri açmak/kapatmak için (true/false)

filters:
  - column: "status"
    operator: "contains"
    value: "active"
  - column: "cpu_usage"
    operator: ">"
    value: 80.5
